# Translation file for ../translate/es.po

# msgid ""
# msgstr ""
# "Project-Id-Version: Artscript v2.2\n"
# "Report-Msgid-Bugs-To: \n"
# "POT-Creation-Date: 2013-12-23 21:40-0600\n"
# "PO-Revision-Date: 2013-12-23 21:52-0600\n"
# "Last-Translator: IvanYossi <ghevan@gmail.com>\n"
# "Language-Team: \n"
# "Language: \n"
# "MIME-Version: 1.0\n"
# "Content-Type: text/plain; charset=UTF-8\n"
# "Content-Transfer-Encoding: 8bit\n"
# "X-Poedit-KeywordsList: _;gettext;gettext_noop\n"
# "X-Poedit-Basepath: .\n"
# "X-Poedit-SourceCharset: utf-8\n"
# "X-Poedit-SearchPath-0: .\n"

::msgcat::mcmset es {
{%f => file.ext, %e => ext, %G => WxH} {%f => archivo.ext, %e => ext, %G => WxH}
{%s has no thumb} {%s no tiene miniatura}
{%s has normal thumb} {%s tiene miniatura normal}
{Add custom size. ratio : wxh} {Añadir tamaño personalizado: wxh}
{Add files} {Añadir}
{Add folder} {+Folder}
{All} {Todo}
{All collages assembled} {Todos los mosaicos armados}
{Allow Overwrite} {Sobreescribir}
{Artscript %1$s -- %2$s Files selected} {Artscript %1$s -- %2$s Archivos seleccionados}
{Artscript %s} {Artscript %s}
{Border} {Borde}
{Bottom} {Abajo}
{BottomLeft} {Abajo Iz.}
{BottomRight} {Abajo Der.}
{Center} {Centro}
{Collage} {Collage}
{Collage file name:} {Nombre del Collage:}
{Collections} {Colecciones}
{Color} {Color}
{Colors:} {Colores:}
{Columns:} {Columnas:}
{Compress:} {Comprimir:}
{Concatenation} {Concatenar}
{Configuration file found in %s} {Archivo de configuración encontrado en %s}
{Convert} {Convertir}
{Convert done.} {Conversión terminada}
{Converting... %1$s to %2$s} {Convirtiendo... %1$s a %2$s}
{Crop} {Cortar}
{Error! %s} {Error! %s}
{Estimate size} {Estimar tamaño}
{Extracting file %s} {Extrayendo archivo %s}
{File Conversions Done!} {Conversión de archivos terminada!}
{File extractions finished} {Extracción de archivos terminada}
{Format:} {Formato:}
{Generating preview} {Generando pre visualización}
{ID} {ID}
{Image Strip h} {Tira de Imágenes h}
{Image Strip v} {Tira de Imágenes v}
{Image Style} {Estilo de imagen}
{Image area is bigger} {El área de imagen es mayor:}
{Input} {Entrada}
{Inverse} {Invertir}
{Keep format} {Mismo formato}
{Label:} {Etiqueta:}
{Layouts:} {Mapeo}
{Left} {Izquierda}
{Load preset:} {Cargar opciones:}
{Make Collage} {Crear Collage}
{Make Collage%s} {Crear Collage!}
{Make Collage?} {Crear Collage?}
{Make ORA} {Crear ORA:}
{Mode} {Modo}
{Mode:} {Modo:}
{Need more data} {Necesito datos}
{New} {Nuevo}
{No Thumbnail} {Sin miniatura}
{None} {Nada}
{OnlyGrow} {Agrandar solo}
{OnlyShrink} {Reducir solo}
{Opacity} {Opacidad}
{Output} {Salida}
{Output & Quality} {Salida y Calidad}
{Padding} {Margen}
{Photo sheet} {Hoja de contactos}
{Position} {Posición}
{Powering up Collage Assembly line} {Encendiendo línea de ensamblaje de Collage}
{Prefix and Suffix} {Prefijo y Sufijo}
{Presets config name keys changed drastically from v2.0 to 2.1  If your presets does not load please review presets.config.example file to check the new names.} {Los nombres de las opciones de configuración cambiaron drásticamente de la versión 2.0 a la 2.1. Si tus opciones son ignoradas, no olvides revisar el archivo "presets.config.example" para conocer los nombres nuevos.}
{Preview} {Pre visualizar}
{Program %s not found} {Programa %s no encontrado}
{Quality:} {Calidad:}
{Range:} {Rango:}
{Remove Alfa} {Remover Alfa}
{Remove Selected} {Quitar}
{Rename} {Renombrar}
{Rename finished.} {Renombrado terminado.}
{Renaming...} {Renombrando...}
{Rendering Gimps} {Renderizando Gimps}
{Rendering Ink Scapes} {Renderizando InkScapes}
{Rendering Kriters} {Renderizando Kriters}
{Resize} {Escalar}
{Right} {Derecha}
{Rotation} {Rotación}
{Rows:} {Filas:}
{Scale} {Escalar}
{Select} {Escoger}
{Select:} {Escoger:}
{Size} {Tamaño}
{Size out} {T. Salida}
{Something went wrong, tmp png wasn't created} {Algo salio mal, no se pudo crear el archivo temporal png}
{Square 3x3} {Cuadrado 3x3}
{Starting Convert...} {Comenzando conversión...}
{Starting File extractions...} {Comenzando extracción de archivos...}
{Storyboard} {Storyboard}
{Stretch} {Estirar}
{Style:} {Estilo:}
{Suported Images} {Imágenes soportadas}
{Text Style} {Estilo del texto}
{Thumbnail} {Miniatura}
{Tile size. ratio : w x h} {Tamaño de tesela:}
{Tk drag and drop enabled} {Tk, arrastrar y soltar habilitado}
{Top} {Arriba}
{TopLeft} {Arriba Iz.}
{TopRight} {Arriba Der.}
{Watermark} {Marca de agua}
{Wrap} {Repetir}
{Zero geometry} {Geometría Cero}
{Zoom} {Acercamiento}
{all} {todo}
{bright} {brillante}
{clear} {limpiar}
{dark} {oscuro}
{darker} {negro}
{default} {por defecto}
{error: %s} {error: %s}
{ext.} {ext.}
{file %s found!} {archivo %s encontrado!}
{icon} {ícono}
{image} {imagen}
{inv.} {inv.}
{label} {etiqueta}
{neutral} {neutral}
{percentage} {porcentajes}
{renaming... %s} {rebautizando... %s}
{sels} {sels}
{text} {texto}
{texture} {textura}
{wallpaper} {fondo de escritorio}
{webp lossy} {webp con pérdida}
}
