# Translation file for fr.po

# msgid ""
# msgstr ""
# "Project-Id-Version: Artscript v2.2\n"
# "Report-Msgid-Bugs-To: \n"
# "POT-Creation-Date: 2014-01-23 19:40-0600\n"
# "PO-Revision-Date: 2014-01-23 19:45-0600\n"
# "Last-Translator: Deevad <info@davidrevoy.com>\n"
# "Language-Team: \n"
# "Language: \n"
# "MIME-Version: 1.0\n"
# "Content-Type: text/plain; charset=UTF-8\n"
# "Content-Transfer-Encoding: 8bit\n"
# "X-Poedit-KeywordsList: _;gettext;gettext_noop\n"
# "X-Poedit-Basepath: .\n"
# "X-Poedit-SourceCharset: utf-8\n"
# "X-Poedit-SearchPath-0: .\n"

::msgcat::mcmset fr {
{%f => file.ext, %e => ext, %G => WxH} {%f => fichier.ext, %e => ext, %G => WxH}
{%s file format not supported} {Format de fichier %s non pris en charge}
{%s has no thumb} {%s n'a pas de vignette}
{%s has normal thumb} {%s a une vignette normale}
{%s is not a valid ORA/KRA} {%s n'est pas un fichier ORA/KRA valide}
{%s not a valid PSD file} {%s n'est pas un fichier PSD valide}
{Add custom size. ratio : wxh} {Personnaliser la taille, le ratio: wxh}
{Add files} {Ajouter}
{Add folder} {+Dossier}
{All} {Tout}
{All collages assembled} {Tous les collages assemblé}
{Allow Overwrite} {Permettre l'écrasement}
{Artscript %1$s -- %2$s Files selected} {Artscript %1$s -- %2$s fichiers selectionnés}
{Artscript %s} {Artscript %s}
{Border} {Bordure}
{Bottom} {Bas}
{BottomLeft} {Bas-Gauche.}
{BottomRight} {Bas-Droit}
{Center} {Centre}
{Choose color} {Choisir une couleur}
{Collage} {Collage}
{Collage Background Color} {Couleur du fond}
{Collage Border Color} {Couleur de la bordure}
{Collage Label Color} {Couleur de l'étiquette}
{Collage file name:} {Nom du Collage:}
{Collections} {Collections}
{Color} {Couleur}
{Colors:} {Couleurs:}
{Columns:} {Colonnes:}
{Compress:} {Compresser:}
{Concatenation} {Concatener}
{Configuration file found in %s} {Fichier de configuration trouvé dans %s}
{Convert} {Convertir}
{Convert done.} {Convertion terminé}
{Converting... %1$s to %2$s} {Convertion... %1$s a %2$s}
{Crop} {Recadrer}
{Error! %s} {Erreur! %s}
{Estimate size} {Taille estimée}
{Extracting file %s} {Extraction du fichier %s}
{File Conversions Done!} {Convertion de fichier terminé!}
{File extractions finished} {Convertions de fichiers terminés!}
{Format:} {Format:}
{Generating preview} {Generation d'une prévisualisation}
{ID} {ID}
{Image Strip h} {Suite d'image h}
{Image Strip v} {Suite d'image v}
{Image Style} {style d'image}
{Image area is bigger} {Zone de l'image est plus grande:}
{Input} {Ajout}
{Inverse} {Inverser}
{Keep format} {Garder le format}
{Label:} {Etiquette:}
{Layouts:} {Disposition:}
{Left} {Gauche}
{Load preset:} {Charger la preconfiguration:}
{Make Collage} {Faire le Collage}
{Make Collage%s} {Créer le Collage!}
{Make Collage?} {Créer le Collage?}
{Make ORA} {Faire un ORA:}
{Mode} {Mode}
{Mode:} {Mode:}
{Need more data} {Necessite plus de données}
{New} {Nouveau}
{No Thumbnail} {Sans vignettes}
{No images loaded!} {Pas d'images listées!}
{None} {Rien}
{ORA Image Files Ready!} {Fichier ORA prêt!}
{OnlyGrow} {Seulement Agrandir}
{OnlyShrink} {Seulement rétrecir}
{Opacity} {Opacité}
{Oraizing... %s} {Cretion d'image Ora... %s}
{Output} {Sortie}
{Output & Quality} {Sortie et qualité}
{Padding} {Marge}
{Photo sheet} {Planche de contact}
{Position} {Position}
{Powering up Collage Assembly line} {Motorisation d'un assemblage de collage}
{Prefix and Suffix} {Prefix et Suffix}
{Presets config name keys changed drastically from v2.0 to 2.1  If your presets does not load please review presets.config.example file to check the new names.} {Les fichiers de configurations ont changés depuis v2.0 a 2.1. Si vos presets ne charge pas , merci de reconfigurer presets.config.example et verifier les nouveaux noms.}
{Preview} {Prévisualisation}
{Program %s not found} {Logiciel %s introuvable}
{Quality:} {Qualité:}
{Range:} {Etendu:}
{Remove Alfa} {Supprimer la transparence}
{Remove Selected} {Supprimer les selectionnés}
{Rename} {Renommer}
{Rename Images Done!} {Renommage d'image terminé!}
{Rename finished.} {Renommage terminé.}
{Renaming...} {Renommage...}
{Rendering Gimps} {Rendu de Gimps}
{Rendering Ink Scapes} {Rendu d'InkScapes}
{Rendering Kriters} {Rendu de Krita}
{Resize} {Redimensionner}
{Right} {Droite}
{Rotation} {Rotation}
{Rows:} {Lignes:}
{Scale} {Redimensionné}
{Select} {Selectionné}
{Select:} {Selection:}
{Size} {Taille}
{Size out} {Taille extérieur}
{Something went wrong, tmp png wasn't created} {Quelquechose d'imprevu c'est passé ; et le png temporaire n'a pas pu être crée}
{Square 3x3} {Carré 3x3}
{Starting Convert...} {Début de la convertion...}
{Starting File extractions...} {Début de l'extraction de fichier...}
{Storyboard} {Storyboard}
{Stretch} {Etirer}
{Style:} {Style:}
{Suported Images} {Images supportées}
{Text Style} {Style de texte}
{Thumbnail} {Vignette}
{Tile size. ratio : w x h} {Tamaño de tesela:}
{Tk drag and drop enabled} {Tk, glisser/déposer actif}
{Top} {Haut}
{TopLeft} {Haut-Gauche.}
{TopRight} {Haut-Droit.}
{Watermark} {Filigrane}
{Watermark Text Color} {Couleur du text filigrané}
{Wrap} {Enveloppé}
{Zero geometry} {Dimmension zéro}
{Zoom} {Zoom}
{all} {tous}
{bright} {brillance}
{clear} {effacer}
{dark} {obscurité}
{darker} {plus sombre}
{default} {par défaut}
{error: %s} {erreur: %s}
{ext.} {ext.}
{file %s found!} {fichier %s trouvé!}
{icon} {icone}
{image} {image}
{inv.} {inv.}
{label} {étiquette}
{neutral} {neutre}
{percentage} {pourcentage}
{renaming... %s} {renommage... %s}
{sels} {sels}
{text} {texte}
{texture} {texture}
{wallpaper} {fond d'écran}
{webp lossy} {webp avec perte}
}
